version: '3.1'
services:
  server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:14-alpine
    container_name: stats
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=stats

