drop schema  public cascade ;
create schema  public;
CREATE TABLE IF NOT EXISTS endpoint_hit
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app  VARCHAR(512)                             NOT NULL,
    uri VARCHAR(2048)                              NOT NULL,
    ip VARCHAR(45)                               NOT NULL,
    instant TIMESTAMP without time zone          DEFAULT now() ,
    CONSTRAINT pk_user PRIMARY KEY (id)
    );
